version: '3.8'

services:
  db:
    image: postgres:16
    container_name: portfolio_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jhn
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: